### ISSUE TITLE
老哥，功能开发完了吗？能不能打个包试试效果啊

### ISSUE THREAD

**Issue by TsaiYongChuan** [makeloveandroid/TaoBaoTool#1]
想跟大佬一起学习进步

**Comment by makeloveandroid** [comment]
没有，依赖Xposed，开发的的类似 模拟按键 的秒杀插件！！！我用来抢车厘子的

**Comment by TsaiYongChuan** [comment]
老哥，你的那个微信变音服务器连接错误啊，是不是没有维护啦



---原始邮件---
发件人: "makeloveandroid"<notifications@github.com&gt;
发送时间: 2020年2月12日(周三) 下午4:54
收件人: "makeloveandroid/TaoBaoTool"<TaoBaoTool@noreply.github.com&gt;;
抄送: "TsaiYongChuan"<373275869@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [makeloveandroid/TaoBaoTool] 老哥，功能开发完了吗？能不能打个包试试效果啊 (#1)



没有，依赖Xposed，开发的的类似 模拟按键 的秒杀插件！！！我用来抢车厘子的
