### ISSUE TITLE
当商品属性过多时，页面会无法正常显示确定和取消按钮。

### ISSUE THREAD

**Issue by whoamixx1** [makeloveandroid/TaoBaoTool#11]
如题，当商品属性元素过多会导致 页面无法正常显示全部且不可以滑动到底部，点不到确定或者取消按钮，此时返回按钮无关用相当于假卡死 算是bug吧, 比如ID为 609595793253 就会导致复现这个问题。

多谢作者的无私贡献， 我也是抢了好久车厘子没抢到,在GitHub上找找相关的脚本一类的，没想到就找到你了

**Comment by makeloveandroid** [comment]
谢谢 我看下

**Comment by makeloveandroid** [comment]
以解决
