### ISSUE TITLE
请作者注意规避法律风险。

### ISSUE THREAD

**Issue by whoamixx1** [makeloveandroid/TaoBaoTool#14]
没其他的看到作者这么辛辛苦苦的更新软件，只是想提醒下作者要注意规避法律风险，淘宝的法务部门每年都会找几个制作淘宝抢购软件的作者，进去不少了而且网上也有相关案例，所以我想作者还是提供源码不提供编译后的版本，或者想其他办法规避这方面的法律风险。

**Comment by makeloveandroid** [comment]
好的 还需要注意什么呢？
