### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by willdownup** [makeloveandroid/TaoBaoTool#9]
希望能有购物车秒杀，还有同步淘宝时间失败，已经root

**Comment by makeloveandroid** [comment]
购物车秒杀流程 我没闹明白！！不经常买东西，你可以个给一个可以抢购的物品的连接吗？我熟悉下流程！

**Comment by willdownup** [comment]
> 购物车秒杀流程 我没闹明白！！不经常买东西，你可以个给一个可以抢购的物品的连接吗？我熟悉下流程！

链接: https://pan.baidu.com/s/1av0KCjcwSIOtOGPOL4d6pg 提取码: sn2c，淘助手按照就是按照脚本到规定时间在购物车窗口模拟点击抢，作者可以看看，可能是根据控件来控制抢购吧

**Comment by makeloveandroid** [comment]
嗯 我看了这个了。
